DROP TABLE IF EXISTS `access_list`;
DROP TABLE IF EXISTS `doors`;
DROP TABLE IF EXISTS `emp_access`;
DROP TABLE IF EXISTS `access_level`;
DROP TABLE IF EXISTS `employee`;
DROP TABLE IF EXISTS `department`;

CREATE TABLE department (
	id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
	depName VARCHAR(50) NOT NULL,
	PRIMARY KEY  (id)
)ENGINE=InnoDB;


CREATE TABLE employee (
	id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
	fname VARCHAR(45) NOT NULL,
	lname VARCHAR(45) NOT NULL,
	dept SMALLINT UNSIGNED NOT NULL,
	job VARCHAR(255) NOT NULL,
	PRIMARY KEY  (id),
	CONSTRAINT fk_emp_dept FOREIGN KEY (dept) REFERENCES department(id) ON DELETE CASCADE ON UPDATE CASCADE
)ENGINE=InnoDB;


CREATE TABLE access_level (
	id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
	deptID SMALLINT UNSIGNED NOT NULL,
	PRIMARY KEY (id),
	CONSTRAINT fk_al_dept FOREIGN KEY (deptID) REFERENCES department(id) ON DELETE CASCADE ON UPDATE CASCADE
)ENGINE=InnoDB; 


CREATE TABLE doors (
	id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
	doorName VARCHAR(50) NOT NULL,
	reqAccess SMALLINT UNSIGNED NOT NULL,
	PRIMARY KEY (id),
	CONSTRAINT fk_doors_al FOREIGN KEY (reqAccess) REFERENCES access_level(id) ON DELETE CASCADE ON UPDATE CASCADE
)ENGINE=InnoDB;


CREATE TABLE emp_access (
	EID SMALLINT UNSIGNED NOT NULL,
	AID SMALLINT UNSIGNED NOT NULL,
	PRIMARY KEY (EID, AID),
	CONSTRAINT fk_ea_emp FOREIGN KEY (EID) REFERENCES employee(id) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT fk_ea_al FOREIGN KEY (AID) REFERENCES access_level(id) ON DELETE CASCADE ON UPDATE CASCADE
)ENGINE=InnoDB; 


CREATE TABLE access_list (
	EID SMALLINT UNSIGNED NOT NULL,
	DID SMALLINT UNSIGNED NOT NULL,
	access_time DATETIME NOT NULL,
	PRIMARY KEY (EID, DID, access_time),
	CONSTRAINT fk_al_emp FOREIGN KEY (EID) REFERENCES employee(id) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT fk_al_doors FOREIGN KEY (DID) REFERENCES doors(id) ON DELETE CASCADE ON UPDATE CASCADE
)ENGINE=InnoDB; 
